project_id = "umqehhhpedwqdfjmdjqv"

[functions.classify-transaction]
verify_jwt = false

[functions.classify-transactions]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.manage-user-access]
verify_jwt = false

[functions.process-import]
verify_jwt = false

[functions.seed-categories]
verify_jwt = false

[functions.seed-reconciliation-rules]
verify_jwt = false

[functions.generate-ai-insights]
verify_jwt = false
